// Actions
export const SHOW_EXCLUDE_MODAL = "SHOW_EXCLUDE_MODAL";
export const GET_ITEM_DATA = "GET_ITEM_DATA";
export const GET_KEY_WORD_LIST = "GET_KEY_WORD_LIST";
export const RESET_INIT_BL_CATEGORIES_DATA = "RESET_INIT_BL_CATEGORIES_DATA";
export const RESET_INIT_BL_SELLERS_DATA = "RESET_INIT_BL_SELLERS_DATA";
export const RESET_INIT_BL_KEYWORDS_DATA = "RESET_INIT_BL_KEYWORDS_DATA";
export const RESET_INIT_HL_ITEM_DATA = "RESET_INIT_HL_ITEM_DATA";

// Actions get
export const API_GET_NEW_ITEM_LIST = "API_GET_NEW_ITEM_LIST";
export const API_GET_BLACK_LIST_CATEGORIES = "API_GET_BLACK_LIST_CATEGORIES";
export const API_GET_BLACK_LIST_SELLERS = "API_GET_BLACK_LIST_SELLERS";
export const API_GET_BLACK_LIST_KEYWORDS = "API_GET_BLACK_LIST_KEYWORDS";
export const API_GET_HOT_LIST_ITEM = "API_GET_HOT_LIST_ITEM";
export const API_GET_HOT_ITEM_KEYWORD = "API_GET_HOT_ITEM_KEYWORD";
export const API_GET_HOT_ITEM = "API_GET_HOT_ITEM";
export const API_GET_LIST_MARKET = "API_GET_LIST_MARKET";

//Action post
export const API_POST_BLACK_LIST_CATEGORY = "API_POST_BLACK_LIST_CATEGORY";
export const API_POST_BLACK_LIST_SELLER = "API_POST_BLACK_LIST_SELLER";
export const API_POST_BLACK_LIST_KEYWORD = "API_POST_BLACK_LIST_KEYWORD";
export const API_POST_CLEAR_ALL_DATA = "API_POST_CLEAR_ALL_DATA";

// Add hotItem
export const API_POST_HOT_ITEM = "API_POST_HOT_ITEM";
export const ADD_HOT_ITEM_SUCCESS = "ADD_HOT_ITEM_SUCCESS";
export const ADD_HOT_ITEM_FAIL = "ADD_HOT_ITEM_FAIL";

// Delete hotItem
export const API_DELETE_HOT_ITEM = "API_DELETE_HOT_ITEM";
export const DELETE_HOT_ITEM_SUCCESS = "DELETE_HOT_ITEM_SUCCESS";
export const DELETE_HOT_ITEM_FAIL = "DELETE_HOT_ITEM_FAIL";

//Action delete
export const API_DELETE_BLACK_LIST_CATEGORY = "API_DELETE_BLACK_LIST_CATEGORY";
export const API_DELETE_BLACK_LIST_SELLER = "API_DELETE_BLACK_LIST_SELLER";
export const API_DELETE_BLACK_LIST_KEYWORD = "API_DELETE_BLACK_LIST_KEYWORD";

//Action hotItem keyword
export const API_ADD_HOT_ITEM_KEYWORD = "API_ADD_HOT_ITEM_KEYWORD";
export const ADD_HOT_ITEM_KEYWORD_SUCCESS = "ADD_HOT_ITEM_KEYWORD_SUCCESS";
export const ADD_HOT_ITEM_KEYWORD_FAIL = "ADD_HOT_ITEM_KEYWORD_FAIL";

//Action delete hotItem keyword
export const API_DELETE_HOT_ITEM_KEYWORD = "API_DELETE_HOT_ITEM_KEYWORD";
export const DELETE_HOT_ITEM_KEYWORD_SUCCESS = "DELETE_HOT_ITEM_KEYWORD_SUCCESS";
export const DELETE_HOT_ITEM_KEYWORD_FAIL = "DELETE_HOT_ITEM_KEYWORD_FAIL";

// Update list market
export const API_UPDATE_LIST_MARKET = "API_UPDATE_LIST_MARKET";
export const UPDATE_LIST_MARKET_SUCCESS = "UPDATE_LIST_MARKET_SUCCESS";
export const UPDATE_LIST_MARKET_FAIL = "UPDATE_LIST_MARKET_FAIL";

export const API_DELETE_LIST_MARKET = "API_DELETE_LIST_MARKET";
export const DELETE_LIST_MARKET_SUCCESS = "DELETE_LIST_MARKET_SUCCESS";
export const DELETE_LIST_MARKET_FAIL = "DELETE_LIST_MARKET_FAIL";

export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const API_REFRESH_LOADING = "API_REFRESH_LOADING";

export const NEW_ITEMS_API_GET_LIST_CUSTOM_CONFIG = "NEW_ITEMS_API_GET_LIST_CUSTOM_CONFIG";

export const NEW_ITEMS_API_SAVE_CONFIG_CUSTOM = "NEW_ITEMS_API_SAVE_CONFIG_CUSTOM";
export const NEW_ITEMS_API_SAVE_CONFIG_CUSTOM_SUCCESS = "NEW_ITEMS_API_SAVE_CONFIG_CUSTOM_SUCCESS";
export const NEW_ITEMS_API_SAVE_CONFIG_CUSTOM_FAIL = "NEW_ITEMS_API_SAVE_CONFIG_CUSTOM_FAIL";

export const NEW_ITEMS_API_DELETE_CONFIG_CUSTOM = "NEW_ITEMS_API_DELETE_CONFIG_CUSTOM";
export const NEW_ITEMS_API_DELETE_CONFIG_CUSTOM_SUCCESS = "NEW_ITEMS_API_DELETE_CONFIG_CUSTOM_SUCCESS";
export const NEW_ITEMS_API_DELETE_CONFIG_CUSTOM_FAIL = "NEW_ITEMS_API_DELETE_CONFIG_CUSTOM_FAIL";
